version: '3'

services:
  frontend:
    build: ./client
    container_name: info-client
    ports:
      - "81:81"
    depends_on:
      - backend
    networks:
      - getinfo-network

  backend:
    build: ./server
    container_name: info-back
    ports:
      - "3041:3041"
    depends_on:
      - mongo
    networks:
      - getinfo-network

  mongo:
    image: mongo:4.4.6
    container_name: mongoinfo
    ports:
      - "27021:27017"
    volumes:
      - mongo-data-info:/data/db
    networks:
      - getinfo-network

volumes:
  mongo-data-info:
    

networks:
   getinfo-network:
    driver: bridge
