version: '3'

services:
  backend:
    build:
      context: ./server
    ports:
      - "3041:3041"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/SearchCityInfo
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - "81:81"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:  
